const wordList = [
    { "spell": "a", "pingjia": "あ", "pianjia": "ア" },
    { "spell": "i", "pingjia": "い", "pianjia": "イ" },
    { "spell": "u", "pingjia": "う", "pianjia": "ウ" },
    { "spell": "e", "pingjia": "え", "pianjia": "エ" },
    { "spell": "o", "pingjia": "お", "pianjia": "オ" },
    { "spell": "ka", "pingjia": "か", "pianjia": "カ" },
    { "spell": "ki", "pingjia": "き", "pianjia": "キ" },
    { "spell": "ku", "pingjia": "く", "pianjia": "ク" },
    { "spell": "ke", "pingjia": "け", "pianjia": "ケ" },
    { "spell": "ko", "pingjia": "こ", "pianjia": "コ" },
    { "spell": "sa", "pingjia": "さ", "pianjia": "サ" },
    { "spell": "shi", "pingjia": "し", "pianjia": "シ" },
    { "spell": "su", "pingjia": "す", "pianjia": "ス" },
    { "spell": "se", "pingjia": "せ", "pianjia": "セ" },
    { "spell": "so", "pingjia": "そ", "pianjia": "ソ" },
    { "spell": "ta", "pingjia": "た", "pianjia": "タ" },
    { "spell": "chi", "pingjia": "ち", "pianjia": "チ" },
    { "spell": "tsu", "pingjia": "つ", "pianjia": "ツ" },
    { "spell": "te", "pingjia": "て", "pianjia": "テ" },
    { "spell": "to", "pingjia": "と", "pianjia": "ト" },
    { "spell": "na", "pingjia": "な", "pianjia": "ナ" },
    { "spell": "ni", "pingjia": "に", "pianjia": "ニ" },
    { "spell": "nu", "pingjia": "ぬ", "pianjia": "ヌ" },
    { "spell": "ne", "pingjia": "ね", "pianjia": "ネ" },
    { "spell": "no", "pingjia": "の", "pianjia": "ノ" },
    { "spell": "ha", "pingjia": "は", "pianjia": "ハ" },
    { "spell": "hi", "pingjia": "ひ", "pianjia": "ヒ" },
    { "spell": "fu", "pingjia": "ふ", "pianjia": "フ" },
    { "spell": "he", "pingjia": "へ", "pianjia": "ヘ" },
    { "spell": "ho", "pingjia": "ほ", "pianjia": "ホ" },
    { "spell": "ma", "pingjia": "ま", "pianjia": "マ" },
    { "spell": "mi", "pingjia": "み", "pianjia": "ミ" },
    { "spell": "mu", "pingjia": "む", "pianjia": "ム" },
    { "spell": "me", "pingjia": "め", "pianjia": "メ" },
    { "spell": "mo", "pingjia": "も", "pianjia": "モ" },
    { "spell": "ya", "pingjia": "や", "pianjia": "ヤ" },
    { "spell": "yu", "pingjia": "ゆ", "pianjia": "ユ" },
    { "spell": "yo", "pingjia": "よ", "pianjia": "ヨ" },
    { "spell": "ra", "pingjia": "ら", "pianjia": "ラ" },
    { "spell": "ri", "pingjia": "り", "pianjia": "リ" },
    { "spell": "ru", "pingjia": "る", "pianjia": "ル" },
    { "spell": "re", "pingjia": "れ", "pianjia": "レ" },
    { "spell": "ro", "pingjia": "ろ", "pianjia": "ロ" },
    { "spell": "wa", "pingjia": "わ", "pianjia": "ワ" },
    { "spell": "wo", "pingjia": "を", "pianjia": "ヲ" },
    { "spell": "nn", "pingjia": "ん", "pianjia": "ン" },
    { "spell": "ba", "pingjia": "ば", "pianjia": "バ" },
    { "spell": "bi", "pingjia": "び", "pianjia": "ビ" },
    { "spell": "bu", "pingjia": "ぶ", "pianjia": "ブ" },
    { "spell": "be", "pingjia": "べ", "pianjia": "ベ" },
    { "spell": "bo", "pingjia": "ぼ", "pianjia": "ボ" },
    { "spell": "ga", "pingjia": "が", "pianjia": "ガ" },
    { "spell": "gi", "pingjia": "ぎ", "pianjia": "ギ" },
    { "spell": "gu", "pingjia": "ぐ", "pianjia": "グ" },
    { "spell": "ge", "pingjia": "げ", "pianjia": "ゲ" },
    { "spell": "go", "pingjia": "ご", "pianjia": "ゴ" },
    { "spell": "za", "pingjia": "ざ", "pianjia": "ザ" },
    { "spell": "zi", "pingjia": "じ", "pianjia": "ジ" },
    { "spell": "zu", "pingjia": "ず", "pianjia": "ズ" },
    { "spell": "ze", "pingjia": "ぜ", "pianjia": "ゼ" },
    { "spell": "zo", "pingjia": "ぞ", "pianjia": "ゾ" },
    { "spell": "da", "pingjia": "だ", "pianjia": "ダ" },
    { "spell": "di", "pingjia": "ぢ", "pianjia": "ヂ" },
    { "spell": "du", "pingjia": "づ", "pianjia": "ヅ" },
    { "spell": "de", "pingjia": "で", "pianjia": "デ" },
    { "spell": "do", "pingjia": "ど", "pianjia": "ド" },
    { "spell": "pa", "pingjia": "ぱ", "pianjia": "パ" },
    { "spell": "pi", "pingjia": "ぴ", "pianjia": "ピ" },
    { "spell": "pu", "pingjia": "ぷ", "pianjia": "プ" },
    { "spell": "pe", "pingjia": "ぺ", "pianjia": "ペ" },
    { "spell": "po", "pingjia": "ぽ", "pianjia": "ポ" },
    { "spell": "kya", "pingjia": "きゃ", "pianjia": "キャ" },
    { "spell": "kyu", "pingjia": "きゅ", "pianjia": "キュ" },
    { "spell": "kyo", "pingjia": "きょ", "pianjia": "キョ" },
    { "spell": "sya", "pingjia": "しゃ", "pianjia": "シャ" },
    { "spell": "syu", "pingjia": "しゅ", "pianjia": "シュ" },
    { "spell": "syo", "pingjia": "しょ", "pianjia": "ショ" },
    { "spell": "cha", "pingjia": "ちゃ", "pianjia": "チャ" },
    { "spell": "chu", "pingjia": "ちゅ", "pianjia": "チュ" },
    { "spell": "cho", "pingjia": "ちょ", "pianjia": "チョ" },
    { "spell": "nya", "pingjia": "にゃ", "pianjia": "ニャ" },
    { "spell": "nyu", "pingjia": "にゅ", "pianjia": "ニュ" },
    { "spell": "nyo", "pingjia": "にょ", "pianjia": "ニョ" },
    { "spell": "hya", "pingjia": "ひゃ", "pianjia": "ヒャ" },
    { "spell": "hyu", "pingjia": "ひゅ", "pianjia": "ヒュ" },
    { "spell": "hyo", "pingjia": "ひょ", "pianjia": "ヒョ" },
    { "spell": "mya", "pingjia": "みゃ", "pianjia": "ミャ" },
    { "spell": "myu", "pingjia": "みゅ", "pianjia": "ミュ" },
    { "spell": "myo", "pingjia": "みょ", "pianjia": "ミョ" },
    { "spell": "rya", "pingjia": "りゃ", "pianjia": "リャ" },
    { "spell": "ryu", "pingjia": "りゅ", "pianjia": "リュ" },
    { "spell": "ryo", "pingjia": "りょ", "pianjia": "リョ" },
    { "spell": "bya", "pingjia": "びゃ", "pianjia": "ビャ" },
    { "spell": "byu", "pingjia": "びゅ", "pianjia": "ビュ" },
    { "spell": "byo", "pingjia": "びょ", "pianjia": "ビョ" },
    { "spell": "gya", "pingjia": "ぎゃ", "pianjia": "ギャ" },
    { "spell": "gyu", "pingjia": "ぎゅ", "pianjia": "ギュ" },
    { "spell": "gyo", "pingjia": "ぎょ", "pianjia": "ギョ" },
    { "spell": "zya", "pingjia": "じゃ", "pianjia": "ジャ" },
    { "spell": "zyu", "pingjia": "じゅ", "pianjia": "ジュ" },
    { "spell": "zyo", "pingjia": "じょ", "pianjia": "ジョ" },
    { "spell": "pya", "pingjia": "ぴゃ", "pianjia": "ピャ" },
    { "spell": "pyu", "pingjia": "ぴゅ", "pianjia": "ピュ" },
    { "spell": "pyo", "pingjia": "ぴょ", "pianjia": "ピョ" }
];

const pingjiaList = [
    "あ", "い", "う", "え", "お",
    "か", "き", "く", "け", "こ",
    "さ", "し", "す", "せ", "そ",
    "た", "ち", "つ", "て", "と",
    "な", "に", "ぬ", "ね", "の",
    "は", "ひ", "ふ", "へ", "ほ",
    "ま", "み", "む", "め", "も",
    "や", "ゆ", "よ",
    "ら", "り", "る", "れ", "ろ",
    "わ", "を", "ん",
    "ば", "び", "ぶ", "べ", "ぼ",
    "が", "ぎ", "ぐ", "げ", "ご",
    "ざ", "じ", "ず", "ぜ", "ぞ",
    "だ", "ぢ", "づ", "で", "ど",
    "ぱ", "ぴ", "ぷ", "ぺ", "ぽ",
    "きゃ", "きゅ", "きょ",
    "しゃ", "しゅ", "しょ",
    "ちゃ", "ちゅ", "ちょ",
    "にゃ", "にゅ", "にょ",
    "ひゃ", "ひゅ", "ひょ",
    "みゃ", "みゅ", "みょ",
    "りゃ", "りゅ", "りょ",
    "びゃ", "びゅ", "びょ",
    "ぎゃ", "ぎゅ", "ぎょ",
    "じゃ", "じゅ", "じょ",
    "ぴゃ", "ぴゅ", "ぴょ"
];

const pianjiaList = [
    "ア", "イ", "ウ", "エ", "オ",
    "カ", "キ", "ク", "ケ", "コ",
    "サ", "シ", "ス", "セ", "ソ",
    "タ", "チ", "ツ", "テ", "ト",
    "ナ", "ニ", "ヌ", "ネ", "ノ",
    "ハ", "ヒ", "フ", "ヘ", "ホ",
    "マ", "ミ", "ム", "メ", "モ",
    "ヤ", "ユ", "ヨ",
    "ラ", "リ", "ル", "レ", "ロ",
    "ワ", "ヲ", "ン",
    "バ", "ビ", "ブ", "ベ", "ボ",
    "ガ", "ギ", "グ", "ゲ", "ゴ",
    "ザ", "ジ", "ズ", "ゼ", "ゾ",
    "ダ", "ヂ", "ヅ", "デ", "ド",
    "パ", "ピ", "プ", "ペ", "ポ",
    "キャ", "キュ", "キョ",
    "シャ", "シュ", "ショ",
    "チャ", "チュ", "チョ",
    "ニャ", "ニュ", "ニョ",
    "ヒャ", "ヒュ", "ヒョ",
    "ミャ", "ミュ", "ミョ",
    "リャ", "リュ", "リョ",
    "ビャ", "ビュ", "ビョ",
    "ギャ", "ギュ", "ギョ",
    "ジャ", "ジュ", "ジョ",
    "ピャ", "ピュ", "ピョ"
];

const spellList = [
    "a", "i", "u", "e", "o",
    "ka", "ki", "ku", "ke", "ko",
    "sa", "shi", "su", "se", "so",
    "ta", "chi", "tsu", "te", "to",
    "na", "ni", "nu", "ne", "no",
    "ha", "hi", "fu", "he", "ho",
    "ma", "mi", "mu", "me", "mo",
    "ya", "yu", "yo",
    "ra", "ri", "ru", "re", "ro",
    "wa", "wo", "nn",
    "ba", "bi", "bu", "be", "bo",
    "ga", "gi", "gu", "ge", "go",
    "za", "zi", "zu", "ze", "zo",
    "da", "di", "du", "de", "do",
    "pa", "pi", "pu", "pe", "po",
    "kya", "kyu", "kyo",
    "sya", "syu", "syo",
    "cha", "chu", "cho",
    "nya", "nyu", "nyo",
    "hya", "hyu", "hyo",
    "mya", "myu", "myo",
    "rya", "ryu", "ryo",
    "bya", "byu", "byo",
    "gya", "gyu", "gyo",
    "zya", "zyu", "zyo",
    "pya", "pyu", "pyo"
];

const wordListLengthArr = [46, 71, 104];